### ISSUE TITLE
The dimensions of the board from the front

### ISSUE THREAD

**Issue by retromaniak** [WeActStudio/WeActStudio.EpaperModule#3]
Good morning.  I would like to model a housing for a display module.  However, while the dimensions of the board are well marked in terms of its size and the spacing of the mounting holes, I cannot find information on how the screen is located on it.

I'm talking about the 2.9" module

**Comment by WeActStudio** [comment]
![15e545e7affd77997b3bb4108837301](https://user-images.githubusercontent.com/57818792/216993089-3a464e3f-7355-44e6-8c08-9e3775b9c55d.png)

**Comment by retromaniak** [comment]
Thank you very much.
